version: "3.1"
volumes:
  mysql_data:
    driver: local
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  keycloak:
    image: jboss/keycloak
    container_name: keycloak-container
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: auth
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: 3306
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - mysql
      
