export enum AppErrorsMessages {
  EMAIL_ALREADY_EXISTS = "Email already registered.",
  INVALID_CREDENTIALS = "Invalid credentials.",
  NOT_AUTHORIZED = "Not authorized.",
  NO_TOKEN_PROVIDED = "No token provided.",
  FAIL_AUTH_TOKEN = "Invalid token.",
  ERROR_SIGNUP = "Error signing up.",
  ERROR_SAVE_USER = "Error saving user.",
  ERROR_UPDATE_USER = "Error updating user.",
  ERROR_DELETE_USER = "Error deleting user.",
  USER_ALREADY_EXISTS = "User already registered.",
  USER_NOT_FOUND = "User not found.",
  EMAIL_REQUIRED = "Email required.",
  USER_ALREADY_LOGGEDIN = "User already logged in!",
  NOT_CREATED = "Not created.",
  NOT_UPDATED = "Not updated.",
  NOT_DELETED = "Not deleted.",
  INTERNAL_ERROR = "Internal error.",
  INVALID_REQUEST = "Invalid request.",
  PASSWORDS_NOT_MATCH = "Passwords don't match.",
  PASSWORDS_REQUIRED = "Passwords required.",
}
